image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: local

cache:
 paths:
 - /root/.m2/repository
 
stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.war
docker-build:
  stage: package
  script:
  - docker build -t registry.gitlab.com/karanfss/currency-converter .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker push registry.gitlab.com/karanfss/currency-converter

deploy_dev:
 stage: deploy
 image: ruby:2.3
 script:
 - apt-get update -qy
 - apt-get install -y ruby-dev
 - gem install dpl
 - dpl --provider=heroku --app=currency-converter-stage --api-key=$HEROKU_API_KEY
 only:
 - master
 tags:
 - docker