apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: currency-converter
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: currency-converter
    spec:
      containers:
      - name: currency-converter
        image: registry.gitlab.com/karanfss/currency-converter
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: registry.gitlab.com