spring:
  profiles:
    active: local
      
---

spring:
  profiles: local
  jpa:
    show-sql: true
  mvc:
    view:
      prefix: /
      suffix: .jsp
   
currency:
  cache:
    ttl: 30
    
---

spring:
  profiles: development
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://sql12.freemysqlhosting.net:3306/sql12173536
    username: sql12173536
    password: EEtm6CrXYb
  mvc:
    view:
      prefix: /
      suffix: .jsp
   
currency:
  cache:
    ttl: 30